### ISSUE TITLE
Just General Help / Questions

### ISSUE THREAD

**Issue by shittyfollower** [ShellCode33/CredSLayer#14]
Hey,

I have installed CredSlayer fine - the documentation is really easy to follow, thanks for that.

I can get CredSlayer to listen on Wlan0 - but how can I test if it is working properly? I go to http sites on other clients, like my routers login page - but it does not capture that input? Should it?

Likewise, if I check Outlook on other clients, should it capture the hashes if using POP / IMAP?

I have used Responder before, which works to capture NTLM hashes on my Windows based machine - so wondering if it should be working similar?

Should I use CredSlayer with a wireless device in monitor mode, will that give a greater degree of success? Thanks

**Comment by ShellCode33** [comment]
Hello there, in order for your to get those credentials you must somehow be able to read the packets being transmitted. Fortunately (security-wise) the router you're connected to won't send all the packets it receives to all its clients. It used to be the case back in the days when hubs were popular. Nowadays, in order to capture packets, you must either put yourself in a MITM position or perform the capture directly onto your switch which obviously is able to read packets from all its clients.

Responder is a totally different beast, what it does is that it will poison name resolution on Windows environments. It will trick clients asking for name resolution on your network into believing you are the name resolver. And they somehow blindly trust you and send you NTLM hashes (don't really know why it happens, probably because Microsoft).

**Comment by shittyfollower** [comment]
Hey thanks for that - that all makes sense! I should try it with an ARP spoofer and/or DNS spoofer, say Bettercap?

**Comment by ShellCode33** [comment]
Totally ! Haven't tried the new release of Bettercap but I would this is the kind of tool you need in addition to CredsLayer
